

# for option function
data_breeds = ['abyssinian', 
                'aegean', 
                'american bobtail', 
                'american curl', 
                'american shorthair', 
                'american wirehair', 
                'arabian mau', 
                'balinese', 
                'bambino', 
                'bengal', 
                'birman', 
                'bombay', 
                'british longhair', 
                'british shorthair', 
                'burmese', 'burmilla', 
                'california spangled', 
                'chantilly-tiffany', 
                'chartreux', 
                'chausie', 
                'cheetoh', 
                'colorpoint shorthair', 
                'cornish rex', 'cyprus', 
                'devon rex', 
                'donskoy', 
                'dragon li', 
                'egyptian mau', 
                'european burmese', 
                'exotic shorthair', 
                'havana brown', 
                'himalayan', 
                'japanese bobtail', 
                'javanese', 
                'khao manee', 
                'korat', 
                'kurilian', 
                'laperm', 
                'maine coon', 
                'malayan', 
                'manx', 
                'munchkin', 
                'nebelung', 
                'norwegian forest cat', 
                'ocicat', 
                'oriental', 
                'persian', 
                'pixie-bob', 
                'ragamuffin', 
                'ragdoll', 
                'russian blue', 
                'savannah', 
                'scottish fold', 
                'selkirk rex', 
                'siamese', 
                'siberian', 
                'singapura', 
                'snowshoe', 
                'somali', 
                'sphynx', 
                'tonkinese', 
                'toyger', 
                'turkish angora', 
                'turkish van', 
                'york chocolate']
